### PR TITLE
Milestone 6-Accessibility

### PR DESCRIPTION
**Pull request by skabeo**
**In this pull request we modified the web page to be accessible by all users. The modifications includes;**

- Page title -  we changed the title of the document [here](https://github.com/skabeo/Mobile-Version-2.0/pull/7/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R7)
- Image Text alternatives - we gave an [alternative text](https://github.com/skabeo/Mobile-Version-2.0/pull/7/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R443-R455) to images tag. 
- Text Headings - we gave the web page a meaningful hierarchy of [headings](https://github.com/skabeo/Mobile-Version-2.0/pull/7/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R162-R163).
- Color contrast - no issues found.
- Resize - no issues found.
- Interaction - we made the web page accessible with [keyboard](https://github.com/skabeo/Mobile-Version-2.0/pull/7/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R35-R37). we also gave a [label](https://github.com/skabeo/Mobile-Version-2.0/pull/7/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R415) to the form fields.
- Moving Content - no issues found.
- Multimedia - no issues found.
- The basic structure of the page  - no issues found.

### CODE REVIEW

**Review by frank1738 — COMMENTED** [review]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have done great work on this milestone but there is an issue with your documentation. Kindly remember that all headers are supposed to be available on your readme file except the `faq` section which is optional. Kindly add the `Key features` and `future future` for your readme file to be more descriptive. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by iambenkis — CHANGES_REQUESTED** [review]
# Required Changes :recycle:
almost-there

### Hey Team :wave:

### Highlights :1st_place_medal:

:heavy_check_mark: Following Linters 
:heavy_check_mark: Following GitHub Flow
:heavy_check_mark: Basic Structure is good
:heavy_check_mark: Can be maximized upto 200%

Good job on implementing some of the requirements but there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional suggestions


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @iambenkis in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by skabeo** [comment]
Hello Benjamin,

Per the articles we read, if the image tag doesn't necessarily affect the
information of the web page we can just declare alt without a text.
Hence all alt tag without a text are mere decorations to the web page.

**Review by souad988 — APPROVED** [review]
Hi @skabeo , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6a4a5143327075565a70544d4f34765573302f67697068792e676966


## Highlights
✔Good PR title and summary
✔Good use of github workflow

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
